version: '3.7'
services:

  symfony:
    container_name: redis_symfony
    build:
      context: .docker/symfony
      args:
        TIMEZONE: 'Europe/Paris'
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony

  nginx:
    container_name: redis_nginx
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www/symfony
    env_file:
      - .docker/.env.nginx
    ports:
      - 8010:80
    networks:
      - symfony

  database:
    image: postgres:15-alpine
    container_name: redis_database
    environment:
      POSTGRES_DB: redis
      POSTGRES_PASSWORD: password
      POSTGRES_USER: redis
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
    networks:
      - symfony

  redis:
    container_name: redis_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - symfony

networks:
  symfony: